Phore Wallet Fix
CryptoCashBack-Hub/CCBC pull request #27
Opened 2019-04-01 16:32 UTC by MotoAcidic

2019-04-03 14:23 UTC, Aviator-Coding commented
That check for invalid wallet address will not work

2019-04-03 14:24 UTC, Aviator-Coding requested changes

2019-04-03 14:24 UTC, Aviator-Coding commented on src/main.cpp
> +					if (badStakers.compare(badAddr[i]) == 0 && badAddr[0] == "  ") {
This will not work

2019-04-04 00:04 UTC, MotoAcidic commented
Make sure rewards match up to the rewards voted on in the community.

2019-04-04 00:16 UTC, mattnyy84 approved these changes
Looks Solid to me

2019-04-06 15:03 UTC, Aviator-Coding commented
Did you change the invalidation code?

2019-04-06 15:06 UTC, Aviator-Coding commented
It looks like to me it still will not work. Might want to create a test address and put 10 coins in it and test it. When I run this on https://ideone.com/h60Jnu i still gave me valid stakers. This code seemed to work https://ideone.com/PH3Keo .

2019-04-06 16:13 UTC, MotoAcidic commented
I just corrected it this morning.

2019-04-07 01:10 UTC, Aviator-Coding commented
it will work does not look pretty

2019-04-07 01:10 UTC, Aviator-Coding approved these changes

2019-04-07 01:31 UTC, merged